filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/nginx/access.log
      - /var/log/nginx/error.log

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: ""
  password: ""

setup.kibana:
  host: "http://localhost:5601"
