services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example_app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network

  nginx1:
    image: nginx:latest
    container_name: nginx1
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx1.conf:/etc/nginx/conf.d/default.conf
      - ./site1:/var/www/html
    depends_on:
      - php1
    networks:
      - laravel_network

  nginx2:
    image: nginx:latest
    container_name: nginx2
    ports:
      - "8082:80"
    volumes:
      - ./nginx/nginx2.conf:/etc/nginx/conf.d/default.conf
      - ./site2:/var/www/html
    depends_on:
      - php2
    networks:
      - laravel_network

  php1:
    build:
      context: ./php
    container_name: php1
    volumes:
      - ./site1:/var/www/html
    depends_on:
      - db
    expose:
      - 9000
    networks:
      - laravel_network

  php2:
    build:
      context: ./php
    container_name: php2
    volumes:
      - ./site2:/var/www/html
    depends_on:
      - db
    expose:
      - 9001
    networks:
      - laravel_network
      
volumes:
  mysql_data:

networks:
  laravel_network:
    driver: bridge
