services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example_app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - traefik

  php1:
    container_name: php1
    restart: always
    build:
      context: ./site1
      dockerfile: Dockerfile
    volumes:
      - ./site1:/var/www/html/
    ports:
      - "9000:9000"
    depends_on:
      - db
    networks:
      - traefik

  php2:
    container_name: php2
    restart: always
    build:
      context: ./site2
      dockerfile: Dockerfile
    volumes:
      - ./site2:/var/www/html/
    ports:
      - "9001:9000"
    depends_on:
      - db
    networks:
      - traefik

  nginx1:
    image: nginx:latest
    container_name: nginx1
    depends_on:
      - php1
    volumes:
      - ./nginx/nginx1.conf:/etc/nginx/conf.d/default.conf
      - ./site1:/var/www/html
      - ./nginx/logs/nginx1:/var/log/nginx/nginx1
    labels:
      - "traefik.enable=true"
      # Routage HTTP -> sur le port 80
      - "traefik.http.routers.nginx1.rule=Host(`site1.local`)"
      - "traefik.http.routers.nginx1.entrypoints=web"
      # Routage HTTPS -> sur le port 443
      - "traefik.http.routers.nginx1-secure.rule=Host(`site1.local`)"
      - "traefik.http.routers.nginx1-secure.entrypoints=websecure"
      - "traefik.http.routers.nginx1-secure.tls=true"
      # On N'UTILISE PAS 'tls.certresolver' => on a un certificat auto-signé
      - "traefik.http.services.nginx1.loadbalancer.server.port=80"
    networks:
      - traefik

  nginx2:
    image: nginx:latest
    container_name: nginx2
    depends_on:
      - php2
    volumes:
      - ./nginx/nginx2.conf:/etc/nginx/conf.d/default.conf
      - ./site2:/var/www/html
      - ./nginx/logs/nginx2:/var/log/nginx/nginx2
    labels:
      - "traefik.enable=true"
      # HTTP
      - "traefik.http.routers.nginx2.rule=Host(`site2.local`)"
      - "traefik.http.routers.nginx2.entrypoints=web"
      # HTTPS
      - "traefik.http.routers.nginx2-secure.rule=Host(`site2.local`)"
      - "traefik.http.routers.nginx2-secure.entrypoints=websecure"
      - "traefik.http.routers.nginx2-secure.tls=true"
      - "traefik.http.services.nginx2.loadbalancer.server.port=80"
    networks:
      - traefik

  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      # Active l'API Traefik sur le port 8080 (facultatif)
      - "--api.insecure=true"
      # Providers
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
      # EntryPoints
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
      - "8090:8080" # (facultatif) pour voir le dashboard Traefik
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      # On monte le dossier qui contient le certificat auto-signé
      - "./certs:/certs"
      # On monte la config dynamique
      - "./traefik_dynamic.yml:/etc/traefik/dynamic/traefik_dynamic.yml:ro"
    networks:
      - traefik

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.2
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.6.2
    container_name: filebeat
    user: root
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./nginx/logs:/nginx-logs:ro
    depends_on:
      - elasticsearch
    command: filebeat -e -strict.perms=false
    networks:
      - traefik

networks:
  traefik:
    external: false

volumes:
  mysql_data:
  es_data: