version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example_app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d

  nginx1:
    image: nginx:latest
    restart: always
    container_name: nginx1
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx1.conf:/etc/nginx/conf.d/default.conf
      - ./site1:/var/www/html
      - ./nginx/logs/nginx1:/var/log/nginx
    depends_on:
      - php1

  nginx2:
    image: nginx:latest
    restart: always
    container_name: nginx2
    ports:
      - "8082:80"
    volumes:
      - ./nginx/nginx2.conf:/etc/nginx/conf.d/default.conf
      - ./site2:/var/www/html
      - ./nginx/logs/nginx2:/var/log/nginx
    depends_on:
      - php2

  php1:
    restart: always
    build:
      context: ./site1
      dockerfile: Dockerfile
    depends_on:
      - db
      - mailhog
    ports:
      - 9000:9000
    environment:
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
    command: >
      sh -c "php artisan migrate:fresh --seed && php-fpm"

  php2:
    restart: always
    build:
      context: ./site2
      dockerfile: Dockerfile
    depends_on:
      - db
      - mailhog
    ports:
      - 9001:9000
    environment:
      MAIL_HOST: mailhog
      MAIL_PORT: 1025

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.2
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.6.2
    container_name: filebeat
    user: root
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./nginx/logs:/nginx-logs:ro
    depends_on:
      - elasticsearch
    command: filebeat -e -strict.perms=false

volumes:
  mysql_data:
  es_data: